# Generated by Django 4.1.2 on 2022-10-11 23:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lasvacances', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='suite',
            name='price',
            field=models.CharField(default=0, max_length=50),
            preserve_default=False,
        ),
    ]
